-- 为业务表及字段补充中文注释（MySQL COMMENT），便于 DBA / 报表 / 数据字典查阅。
-- 不修改 Flyway 历史脚本；已存在库通过本版本一次性落库。

-- ========== 账套与组织 ==========
ALTER TABLE ledger COMMENT = '账套（法人/核算主体）';
ALTER TABLE ledger
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN code VARCHAR(64) NOT NULL COMMENT '账套编码',
    MODIFY COLUMN name VARCHAR(255) NOT NULL COMMENT '账套名称',
    MODIFY COLUMN u9_ledger_code VARCHAR(64) NULL COMMENT 'U9 账套编码',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

ALTER TABLE org_unit COMMENT = '组织单元（采购组织等）';
ALTER TABLE org_unit
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN ledger_id BIGINT NOT NULL COMMENT '所属账套ID',
    MODIFY COLUMN org_type VARCHAR(32) NOT NULL COMMENT '组织类型（如 PROCUREMENT 采购组织）',
    MODIFY COLUMN code VARCHAR(64) NOT NULL COMMENT '组织编码',
    MODIFY COLUMN name VARCHAR(255) NOT NULL COMMENT '组织名称',
    MODIFY COLUMN u9_org_code VARCHAR(64) NULL COMMENT 'U9 组织编码',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

ALTER TABLE warehouse COMMENT = '仓库（隶属采购组织）';
ALTER TABLE warehouse
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN procurement_org_id BIGINT NOT NULL COMMENT '采购组织ID',
    MODIFY COLUMN code VARCHAR(64) NOT NULL COMMENT '仓库编码',
    MODIFY COLUMN name VARCHAR(255) NOT NULL COMMENT '仓库名称',
    MODIFY COLUMN u9_wh_code VARCHAR(64) NULL COMMENT 'U9 仓库编码',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

-- ========== 用户与角色 ==========
ALTER TABLE sys_role COMMENT = '系统角色';
ALTER TABLE sys_role
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN code VARCHAR(64) NOT NULL COMMENT '角色编码',
    MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '角色名称',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

ALTER TABLE sys_user COMMENT = '系统用户（含管理端与门户供应商账号）';
ALTER TABLE sys_user
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN username VARCHAR(64) NOT NULL COMMENT '登录名',
    MODIFY COLUMN password_hash VARCHAR(255) NOT NULL COMMENT '密码哈希（BCrypt）',
    MODIFY COLUMN display_name VARCHAR(128) NULL COMMENT '显示名称',
    MODIFY COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
    MODIFY COLUMN default_procurement_org_id BIGINT NULL COMMENT '默认采购组织ID',
    MODIFY COLUMN supplier_id BIGINT NULL COMMENT '关联供应商ID（门户用户）',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

ALTER TABLE sys_user_role COMMENT = '用户-角色关联';
ALTER TABLE sys_user_role
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户ID',
    MODIFY COLUMN role_id BIGINT NOT NULL COMMENT '角色ID';

-- ========== 主数据 ==========
ALTER TABLE supplier COMMENT = '供应商主数据';
ALTER TABLE supplier
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN code VARCHAR(64) NOT NULL COMMENT '供应商编码',
    MODIFY COLUMN name VARCHAR(255) NOT NULL COMMENT '供应商名称',
    MODIFY COLUMN u9_vendor_code VARCHAR(64) NULL COMMENT 'U9 供应商编码',
    MODIFY COLUMN tax_id VARCHAR(64) NULL COMMENT '税号',
    MODIFY COLUMN lifecycle_status VARCHAR(32) NOT NULL DEFAULT 'QUALIFIED' COMMENT '生命周期状态（如合格/待审核/黑名单等）',
    MODIFY COLUMN contact_name VARCHAR(128) NULL COMMENT '联系人姓名',
    MODIFY COLUMN contact_phone VARCHAR(64) NULL COMMENT '联系电话',
    MODIFY COLUMN contact_email VARCHAR(128) NULL COMMENT '联系邮箱',
    MODIFY COLUMN address VARCHAR(500) NULL COMMENT '地址',
    MODIFY COLUMN bank_name VARCHAR(128) NULL COMMENT '开户银行',
    MODIFY COLUMN bank_account VARCHAR(64) NULL COMMENT '银行账号',
    MODIFY COLUMN business_scope VARCHAR(1000) NULL COMMENT '经营范围',
    MODIFY COLUMN registration_remark VARCHAR(1000) NULL COMMENT '注册/准入备注',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

ALTER TABLE supplier_org_scope COMMENT = '供应商可协作的采购组织授权范围';
ALTER TABLE supplier_org_scope
    MODIFY COLUMN supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    MODIFY COLUMN procurement_org_id BIGINT NOT NULL COMMENT '采购组织ID';

ALTER TABLE material_item COMMENT = '物料主数据';
ALTER TABLE material_item
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN code VARCHAR(64) NOT NULL COMMENT '物料编码',
    MODIFY COLUMN name VARCHAR(255) NOT NULL COMMENT '物料名称',
    MODIFY COLUMN uom VARCHAR(32) NOT NULL COMMENT '计量单位',
    MODIFY COLUMN u9_item_code VARCHAR(64) NULL COMMENT 'U9 料品编码',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

-- ========== 采购订单 ==========
ALTER TABLE po_number_seq COMMENT = '采购订单号按组织年度序号';
ALTER TABLE po_number_seq
    MODIFY COLUMN procurement_org_id BIGINT NOT NULL COMMENT '采购组织ID',
    MODIFY COLUMN year_val INT NOT NULL COMMENT '年份',
    MODIFY COLUMN seq_value BIGINT NOT NULL DEFAULT 0 COMMENT '当前流水号';

ALTER TABLE purchase_order COMMENT = '采购订单头';
ALTER TABLE purchase_order
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN po_no VARCHAR(64) NOT NULL COMMENT '采购订单号',
    MODIFY COLUMN procurement_org_id BIGINT NOT NULL COMMENT '采购组织ID',
    MODIFY COLUMN ledger_id BIGINT NOT NULL COMMENT '账套ID',
    MODIFY COLUMN supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    MODIFY COLUMN currency VARCHAR(8) NOT NULL DEFAULT 'CNY' COMMENT '币种',
    MODIFY COLUMN `status` VARCHAR(32) NOT NULL COMMENT '订单状态（草稿/待审/已审核/已发布等）',
    MODIFY COLUMN revision_no INT NOT NULL DEFAULT 1 COMMENT '版本/修订号',
    MODIFY COLUMN remark VARCHAR(2000) NULL COMMENT '备注',
    MODIFY COLUMN export_status VARCHAR(32) NOT NULL DEFAULT 'NOT_EXPORTED' COMMENT '导出 U9 状态',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

ALTER TABLE purchase_order_line COMMENT = '采购订单行';
ALTER TABLE purchase_order_line
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN purchase_order_id BIGINT NOT NULL COMMENT '采购订单头ID',
    MODIFY COLUMN line_no INT NOT NULL COMMENT '行号',
    MODIFY COLUMN material_id BIGINT NOT NULL COMMENT '物料ID',
    MODIFY COLUMN qty DECIMAL(19, 4) NOT NULL COMMENT '订购数量',
    MODIFY COLUMN uom VARCHAR(32) NOT NULL COMMENT '单位',
    MODIFY COLUMN unit_price DECIMAL(19, 4) NOT NULL COMMENT '单价',
    MODIFY COLUMN amount DECIMAL(19, 4) NOT NULL COMMENT '金额',
    MODIFY COLUMN requested_date DATE NULL COMMENT '要求到货日',
    MODIFY COLUMN warehouse_id BIGINT NOT NULL COMMENT '收货仓库ID',
    MODIFY COLUMN received_qty DECIMAL(19, 4) NOT NULL DEFAULT 0 COMMENT '已收货数量',
    MODIFY COLUMN confirmed_qty DECIMAL(19, 4) NULL COMMENT '供应商确认数量',
    MODIFY COLUMN promised_date DATE NULL COMMENT '承诺交期',
    MODIFY COLUMN supplier_remark VARCHAR(500) NULL COMMENT '供应商行备注',
    MODIFY COLUMN confirmed_at TIMESTAMP(6) NULL COMMENT '行确认时间',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

-- ========== ASN 与收货 ==========
ALTER TABLE asn_number_seq COMMENT = 'ASN 单号按组织年度序号';
ALTER TABLE asn_number_seq
    MODIFY COLUMN procurement_org_id BIGINT NOT NULL COMMENT '采购组织ID',
    MODIFY COLUMN year_val INT NOT NULL COMMENT '年份',
    MODIFY COLUMN seq_value BIGINT NOT NULL DEFAULT 0 COMMENT '当前流水号';

ALTER TABLE asn_notice COMMENT = '发货通知 ASN 头';
ALTER TABLE asn_notice
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN asn_no VARCHAR(64) NOT NULL COMMENT 'ASN 单号',
    MODIFY COLUMN purchase_order_id BIGINT NOT NULL COMMENT '采购订单ID',
    MODIFY COLUMN supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    MODIFY COLUMN procurement_org_id BIGINT NOT NULL COMMENT '采购组织ID',
    MODIFY COLUMN ship_date DATE NOT NULL COMMENT '发货日期',
    MODIFY COLUMN eta_date DATE NULL COMMENT '预计到达日',
    MODIFY COLUMN carrier VARCHAR(255) NULL COMMENT '承运商',
    MODIFY COLUMN tracking_no VARCHAR(128) NULL COMMENT '运单号',
    MODIFY COLUMN remark VARCHAR(1000) NULL COMMENT '备注',
    MODIFY COLUMN `status` VARCHAR(32) NOT NULL COMMENT 'ASN 状态',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

ALTER TABLE asn_line COMMENT = '发货通知 ASN 行';
ALTER TABLE asn_line
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN asn_notice_id BIGINT NOT NULL COMMENT 'ASN 头ID',
    MODIFY COLUMN purchase_order_line_id BIGINT NOT NULL COMMENT '采购订单行ID',
    MODIFY COLUMN line_no INT NOT NULL COMMENT '行号',
    MODIFY COLUMN ship_qty DECIMAL(19, 4) NOT NULL COMMENT '发货数量',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

ALTER TABLE gr_number_seq COMMENT = '收货单号按组织年度序号';
ALTER TABLE gr_number_seq
    MODIFY COLUMN procurement_org_id BIGINT NOT NULL COMMENT '采购组织ID',
    MODIFY COLUMN year_val INT NOT NULL COMMENT '年份',
    MODIFY COLUMN seq_value BIGINT NOT NULL DEFAULT 0 COMMENT '当前流水号';

ALTER TABLE goods_receipt COMMENT = '收货单头';
ALTER TABLE goods_receipt
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN gr_no VARCHAR(64) NOT NULL COMMENT '收货单号',
    MODIFY COLUMN procurement_org_id BIGINT NOT NULL COMMENT '采购组织ID',
    MODIFY COLUMN ledger_id BIGINT NOT NULL COMMENT '账套ID',
    MODIFY COLUMN supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    MODIFY COLUMN warehouse_id BIGINT NOT NULL COMMENT '仓库ID',
    MODIFY COLUMN purchase_order_id BIGINT NOT NULL COMMENT '采购订单ID',
    MODIFY COLUMN receipt_date DATE NOT NULL COMMENT '收货日期',
    MODIFY COLUMN remark VARCHAR(1000) NULL COMMENT '备注',
    MODIFY COLUMN export_status VARCHAR(32) NOT NULL DEFAULT 'NOT_EXPORTED' COMMENT '导出 U9 状态',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

ALTER TABLE goods_receipt_line COMMENT = '收货单行';
ALTER TABLE goods_receipt_line
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN goods_receipt_id BIGINT NOT NULL COMMENT '收货单头ID',
    MODIFY COLUMN purchase_order_line_id BIGINT NOT NULL COMMENT '采购订单行ID',
    MODIFY COLUMN asn_line_id BIGINT NULL COMMENT 'ASN 行ID（可空）',
    MODIFY COLUMN line_no INT NOT NULL COMMENT '行号',
    MODIFY COLUMN received_qty DECIMAL(19, 4) NOT NULL COMMENT '实收数量',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

-- ========== 审计日志 ==========
ALTER TABLE audit_log COMMENT = '操作审计日志';
ALTER TABLE audit_log
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN user_id BIGINT NULL COMMENT '操作用户ID',
    MODIFY COLUMN username VARCHAR(64) NULL COMMENT '操作用户名',
    MODIFY COLUMN action VARCHAR(64) NOT NULL COMMENT '动作编码',
    MODIFY COLUMN entity_type VARCHAR(64) NULL COMMENT '实体类型',
    MODIFY COLUMN entity_id BIGINT NULL COMMENT '实体主键',
    MODIFY COLUMN detail VARCHAR(2000) NULL COMMENT '详情（JSON/文本）',
    MODIFY COLUMN ip_address VARCHAR(64) NULL COMMENT '来源 IP',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '记录时间';

-- ========== 请购 ==========
ALTER TABLE purchase_requisition COMMENT = '请购单头';
ALTER TABLE purchase_requisition
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN pr_no VARCHAR(64) NOT NULL COMMENT '请购单号',
    MODIFY COLUMN procurement_org_id BIGINT NOT NULL COMMENT '采购组织ID',
    MODIFY COLUMN ledger_id BIGINT NOT NULL COMMENT '账套ID',
    MODIFY COLUMN requester_name VARCHAR(128) NULL COMMENT '申请人',
    MODIFY COLUMN department VARCHAR(128) NULL COMMENT '申请部门',
    MODIFY COLUMN `status` VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '请购状态',
    MODIFY COLUMN remark VARCHAR(2000) NULL COMMENT '备注',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

ALTER TABLE purchase_requisition_line COMMENT = '请购单行';
ALTER TABLE purchase_requisition_line
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN pr_id BIGINT NOT NULL COMMENT '请购单头ID',
    MODIFY COLUMN line_no INT NOT NULL COMMENT '行号',
    MODIFY COLUMN material_id BIGINT NOT NULL COMMENT '物料ID',
    MODIFY COLUMN qty DECIMAL(19, 4) NOT NULL COMMENT '请购数量',
    MODIFY COLUMN uom VARCHAR(32) NOT NULL COMMENT '单位',
    MODIFY COLUMN unit_price DECIMAL(19, 4) NULL COMMENT '参考单价',
    MODIFY COLUMN requested_date DATE NULL COMMENT '需求日期',
    MODIFY COLUMN warehouse_id BIGINT NULL COMMENT '建议收货仓库ID',
    MODIFY COLUMN supplier_id BIGINT NULL COMMENT '建议供应商ID',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '行备注',
    MODIFY COLUMN converted_po_id BIGINT NULL COMMENT '已转采购订单ID',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

ALTER TABLE pr_number_seq COMMENT = '请购单号按组织年度序号';
ALTER TABLE pr_number_seq
    MODIFY COLUMN procurement_org_id BIGINT NOT NULL COMMENT '采购组织ID',
    MODIFY COLUMN year_val INT NOT NULL COMMENT '年份',
    MODIFY COLUMN seq_value BIGINT NOT NULL DEFAULT 0 COMMENT '当前流水号';

-- ========== 审批 ==========
ALTER TABLE approval_rule COMMENT = '审批规则';
ALTER TABLE approval_rule
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN doc_type VARCHAR(32) NOT NULL COMMENT '单据类型（PO/PR 等）',
    MODIFY COLUMN min_amount DECIMAL(19, 4) NULL DEFAULT 0 COMMENT '金额下限（含）',
    MODIFY COLUMN max_amount DECIMAL(19, 4) NULL COMMENT '金额上限（不含，可空）',
    MODIFY COLUMN approval_level INT NOT NULL DEFAULT 1 COMMENT '审批层级',
    MODIFY COLUMN approver_role VARCHAR(64) NOT NULL COMMENT '审批人角色编码',
    MODIFY COLUMN description VARCHAR(255) NULL COMMENT '规则说明',
    MODIFY COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

ALTER TABLE approval_instance COMMENT = '审批实例';
ALTER TABLE approval_instance
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN doc_type VARCHAR(32) NOT NULL COMMENT '单据类型',
    MODIFY COLUMN doc_id BIGINT NOT NULL COMMENT '单据业务主键',
    MODIFY COLUMN doc_no VARCHAR(64) NULL COMMENT '单据编号',
    MODIFY COLUMN total_amount DECIMAL(19, 4) NULL COMMENT '单据总金额（用于规则匹配）',
    MODIFY COLUMN `status` VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '审批状态',
    MODIFY COLUMN current_level INT NOT NULL DEFAULT 1 COMMENT '当前审批层级',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

ALTER TABLE approval_step COMMENT = '审批步骤记录';
ALTER TABLE approval_step
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN instance_id BIGINT NOT NULL COMMENT '审批实例ID',
    MODIFY COLUMN step_level INT NOT NULL COMMENT '步骤层级',
    MODIFY COLUMN approver_role VARCHAR(64) NOT NULL COMMENT '审批人角色',
    MODIFY COLUMN approver_id BIGINT NULL COMMENT '审批人用户ID',
    MODIFY COLUMN approver_name VARCHAR(128) NULL COMMENT '审批人姓名',
    MODIFY COLUMN `action` VARCHAR(32) NULL COMMENT '审批动作（通过/驳回等）',
    MODIFY COLUMN `comment` VARCHAR(1000) NULL COMMENT '审批意见',
    MODIFY COLUMN acted_at TIMESTAMP(6) NULL COMMENT '审批时间',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

-- ========== 绩效 ==========
ALTER TABLE perf_template COMMENT = '供应商绩效模板';
ALTER TABLE perf_template
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '模板名称',
    MODIFY COLUMN description VARCHAR(500) NULL COMMENT '模板说明',
    MODIFY COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

ALTER TABLE perf_dimension COMMENT = '绩效维度';
ALTER TABLE perf_dimension
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN template_id BIGINT NOT NULL COMMENT '模板ID',
    MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '维度名称',
    MODIFY COLUMN weight DECIMAL(5, 2) NOT NULL DEFAULT 0 COMMENT '权重',
    MODIFY COLUMN description VARCHAR(500) NULL COMMENT '维度说明',
    MODIFY COLUMN sort_order INT NOT NULL DEFAULT 0 COMMENT '排序',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

ALTER TABLE perf_evaluation COMMENT = '供应商绩效评估';
ALTER TABLE perf_evaluation
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    MODIFY COLUMN template_id BIGINT NOT NULL COMMENT '模板ID',
    MODIFY COLUMN period VARCHAR(32) NOT NULL COMMENT '考核期间（如 2026Q1）',
    MODIFY COLUMN total_score DECIMAL(5, 2) NULL COMMENT '总分',
    MODIFY COLUMN grade VARCHAR(16) NULL COMMENT '等级',
    MODIFY COLUMN evaluator_name VARCHAR(128) NULL COMMENT '评估人',
    MODIFY COLUMN `status` VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '评估状态',
    MODIFY COLUMN remark VARCHAR(1000) NULL COMMENT '备注',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

ALTER TABLE perf_score COMMENT = '绩效评分明细';
ALTER TABLE perf_score
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN evaluation_id BIGINT NOT NULL COMMENT '评估ID',
    MODIFY COLUMN dimension_id BIGINT NOT NULL COMMENT '维度ID',
    MODIFY COLUMN score DECIMAL(5, 2) NOT NULL DEFAULT 0 COMMENT '得分',
    MODIFY COLUMN `comment` VARCHAR(500) NULL COMMENT '评语',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

-- ========== 发票与对账 ==========
-- 列定义以 V8 为准（当前库无税务/状态时间等扩展列）
ALTER TABLE invoice COMMENT = '发票头';
ALTER TABLE invoice
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN invoice_no VARCHAR(64) NOT NULL COMMENT '发票单号',
    MODIFY COLUMN supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    MODIFY COLUMN procurement_org_id BIGINT NOT NULL COMMENT '采购组织ID',
    MODIFY COLUMN invoice_date DATE NOT NULL COMMENT '开票日期',
    MODIFY COLUMN total_amount DECIMAL(19, 4) NOT NULL COMMENT '总金额',
    MODIFY COLUMN tax_amount DECIMAL(19, 4) DEFAULT 0 COMMENT '税额',
    MODIFY COLUMN currency VARCHAR(8) NOT NULL DEFAULT 'CNY' COMMENT '币种',
    MODIFY COLUMN `status` VARCHAR(32) NOT NULL DEFAULT 'SUBMITTED' COMMENT '发票状态',
    MODIFY COLUMN remark VARCHAR(1000) NULL COMMENT '备注',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

ALTER TABLE invoice_line COMMENT = '发票行';
ALTER TABLE invoice_line
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN invoice_id BIGINT NOT NULL COMMENT '发票头ID',
    MODIFY COLUMN line_no INT NOT NULL COMMENT '行号',
    MODIFY COLUMN purchase_order_id BIGINT NULL COMMENT '关联采购订单ID',
    MODIFY COLUMN purchase_order_line_id BIGINT NULL COMMENT '关联采购订单行ID',
    MODIFY COLUMN goods_receipt_id BIGINT NULL COMMENT '关联收货单ID',
    MODIFY COLUMN material_code VARCHAR(64) NULL COMMENT '物料编码（快照）',
    MODIFY COLUMN material_name VARCHAR(255) NULL COMMENT '物料名称（快照）',
    MODIFY COLUMN qty DECIMAL(19, 4) NOT NULL COMMENT '数量',
    MODIFY COLUMN unit_price DECIMAL(19, 4) NOT NULL COMMENT '单价',
    MODIFY COLUMN amount DECIMAL(19, 4) NOT NULL COMMENT '金额',
    MODIFY COLUMN tax_rate DECIMAL(5, 2) NULL DEFAULT 0 COMMENT '税率（%）',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

ALTER TABLE reconciliation COMMENT = '对账单头';
ALTER TABLE reconciliation
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN recon_no VARCHAR(64) NOT NULL COMMENT '对账单号',
    MODIFY COLUMN supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    MODIFY COLUMN procurement_org_id BIGINT NOT NULL COMMENT '采购组织ID',
    MODIFY COLUMN period_from DATE NULL COMMENT '对账期间起',
    MODIFY COLUMN period_to DATE NULL COMMENT '对账期间止',
    MODIFY COLUMN po_amount DECIMAL(19, 4) NULL DEFAULT 0 COMMENT '采购订单金额汇总',
    MODIFY COLUMN gr_amount DECIMAL(19, 4) NULL DEFAULT 0 COMMENT '收货金额汇总',
    MODIFY COLUMN invoice_amount DECIMAL(19, 4) NULL DEFAULT 0 COMMENT '发票金额汇总',
    MODIFY COLUMN diff_amount DECIMAL(19, 4) NULL DEFAULT 0 COMMENT '差异金额',
    MODIFY COLUMN `status` VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '对账状态（含双方确认等）',
    MODIFY COLUMN remark VARCHAR(1000) NULL COMMENT '备注',
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT '更新时间';

-- ========== 供应商审核 / 通知 / 质量 ==========
ALTER TABLE supplier_audit COMMENT = '供应商审核记录';
ALTER TABLE supplier_audit
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    MODIFY COLUMN audit_type VARCHAR(32) NOT NULL COMMENT '审核类型（准入/年度/整改等）',
    MODIFY COLUMN audit_date DATE NOT NULL COMMENT '审核日期',
    MODIFY COLUMN result VARCHAR(32) NOT NULL COMMENT '审核结论',
    MODIFY COLUMN score INT NULL COMMENT '评分',
    MODIFY COLUMN auditor_name VARCHAR(64) NULL COMMENT '审核人',
    MODIFY COLUMN remark VARCHAR(1000) NULL COMMENT '备注',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE notification COMMENT = '站内通知/消息';
ALTER TABLE notification
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN recipient_user_id BIGINT NULL COMMENT '接收用户ID',
    MODIFY COLUMN recipient_supplier_id BIGINT NULL COMMENT '接收供应商ID',
    MODIFY COLUMN title VARCHAR(255) NOT NULL COMMENT '标题',
    MODIFY COLUMN content VARCHAR(2000) NULL COMMENT '内容',
    MODIFY COLUMN category VARCHAR(32) NOT NULL DEFAULT 'SYSTEM' COMMENT '分类（系统/审批/交货/发票等）',
    MODIFY COLUMN ref_type VARCHAR(32) NULL COMMENT '关联业务类型',
    MODIFY COLUMN ref_id BIGINT NULL COMMENT '关联业务主键',
    MODIFY COLUMN is_read TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已读',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE quality_inspection COMMENT = '质量检验';
ALTER TABLE quality_inspection
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN inspection_no VARCHAR(64) NOT NULL COMMENT '检验单号',
    MODIFY COLUMN goods_receipt_id BIGINT NOT NULL COMMENT '收货单ID',
    MODIFY COLUMN supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    MODIFY COLUMN procurement_org_id BIGINT NOT NULL COMMENT '采购组织ID',
    MODIFY COLUMN inspection_date DATE NOT NULL COMMENT '检验日期',
    MODIFY COLUMN inspector_name VARCHAR(64) NULL COMMENT '检验员',
    MODIFY COLUMN result VARCHAR(32) NOT NULL COMMENT '检验结论',
    MODIFY COLUMN total_qty DECIMAL(19, 4) NOT NULL COMMENT '检验总数量',
    MODIFY COLUMN qualified_qty DECIMAL(19, 4) NOT NULL DEFAULT 0 COMMENT '合格数量',
    MODIFY COLUMN defect_qty DECIMAL(19, 4) NOT NULL DEFAULT 0 COMMENT '不良数量',
    MODIFY COLUMN defect_type VARCHAR(128) NULL COMMENT '不良类型',
    MODIFY COLUMN remark VARCHAR(1000) NULL COMMENT '备注',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE corrective_action COMMENT = '纠正措施（8D/整改）';
ALTER TABLE corrective_action
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN ca_no VARCHAR(64) NOT NULL COMMENT '纠正措施单号',
    MODIFY COLUMN inspection_id BIGINT NULL COMMENT '关联检验单ID',
    MODIFY COLUMN supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    MODIFY COLUMN procurement_org_id BIGINT NOT NULL COMMENT '采购组织ID',
    MODIFY COLUMN issue_description VARCHAR(2000) NOT NULL COMMENT '问题描述',
    MODIFY COLUMN root_cause VARCHAR(2000) NULL COMMENT '根本原因',
    MODIFY COLUMN corrective_measures VARCHAR(2000) NULL COMMENT '纠正措施',
    MODIFY COLUMN due_date DATE NULL COMMENT '要求完成日',
    MODIFY COLUMN `status` VARCHAR(32) NOT NULL DEFAULT 'OPEN' COMMENT '状态',
    MODIFY COLUMN closed_date DATE NULL COMMENT '关闭日期',
    MODIFY COLUMN remark VARCHAR(1000) NULL COMMENT '备注',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- ========== 询价 RFQ ==========
ALTER TABLE rfq COMMENT = '询价单头';
ALTER TABLE rfq
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN rfq_no VARCHAR(64) NOT NULL COMMENT '询价单号',
    MODIFY COLUMN title VARCHAR(255) NOT NULL COMMENT '标题',
    MODIFY COLUMN procurement_org_id BIGINT NOT NULL COMMENT '采购组织ID',
    MODIFY COLUMN `status` VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '询价状态',
    MODIFY COLUMN publish_date DATE NULL COMMENT '发布日期',
    MODIFY COLUMN deadline DATE NULL COMMENT '报价截止日',
    MODIFY COLUMN remark VARCHAR(2000) NULL COMMENT '备注',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE rfq_line COMMENT = '询价单行';
ALTER TABLE rfq_line
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN rfq_id BIGINT NOT NULL COMMENT '询价单头ID',
    MODIFY COLUMN line_no INT NOT NULL COMMENT '行号',
    MODIFY COLUMN material_id BIGINT NOT NULL COMMENT '物料ID',
    MODIFY COLUMN qty DECIMAL(19, 4) NOT NULL COMMENT '数量',
    MODIFY COLUMN uom VARCHAR(32) NOT NULL COMMENT '单位',
    MODIFY COLUMN specification VARCHAR(500) NULL COMMENT '规格要求',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '行备注',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE rfq_invitation COMMENT = '询价邀请（受邀供应商）';
ALTER TABLE rfq_invitation
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN rfq_id BIGINT NOT NULL COMMENT '询价单ID',
    MODIFY COLUMN supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    MODIFY COLUMN invited_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '邀请时间',
    MODIFY COLUMN responded TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已响应',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE rfq_quotation COMMENT = '供应商报价头';
ALTER TABLE rfq_quotation
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN rfq_id BIGINT NOT NULL COMMENT '询价单ID',
    MODIFY COLUMN supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    MODIFY COLUMN total_amount DECIMAL(19, 4) NULL COMMENT '报价总金额',
    MODIFY COLUMN currency VARCHAR(8) NOT NULL DEFAULT 'CNY' COMMENT '币种',
    MODIFY COLUMN delivery_days INT NULL COMMENT '交货周期（天）',
    MODIFY COLUMN validity_days INT NULL COMMENT '报价有效天数',
    MODIFY COLUMN remark VARCHAR(2000) NULL COMMENT '备注',
    MODIFY COLUMN submitted_at TIMESTAMP NULL DEFAULT NULL COMMENT '提交时间',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE rfq_quotation_line COMMENT = '供应商报价行';
ALTER TABLE rfq_quotation_line
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN quotation_id BIGINT NOT NULL COMMENT '报价头ID',
    MODIFY COLUMN rfq_line_id BIGINT NOT NULL COMMENT '询价行ID',
    MODIFY COLUMN unit_price DECIMAL(19, 4) NOT NULL COMMENT '单价',
    MODIFY COLUMN amount DECIMAL(19, 4) NULL COMMENT '金额',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '行备注',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- ========== 合同 ==========
ALTER TABLE contract COMMENT = '合同头';
ALTER TABLE contract
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN contract_no VARCHAR(64) NOT NULL COMMENT '合同编号',
    MODIFY COLUMN title VARCHAR(255) NOT NULL COMMENT '合同标题',
    MODIFY COLUMN supplier_id BIGINT NOT NULL COMMENT '供应商ID',
    MODIFY COLUMN procurement_org_id BIGINT NOT NULL COMMENT '采购组织ID',
    MODIFY COLUMN `status` VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '合同状态',
    MODIFY COLUMN contract_type VARCHAR(32) NULL DEFAULT 'FRAMEWORK' COMMENT '合同类型（框架/现货等）',
    MODIFY COLUMN start_date DATE NULL COMMENT '生效日',
    MODIFY COLUMN end_date DATE NULL COMMENT '到期日',
    MODIFY COLUMN total_amount DECIMAL(19, 4) NULL COMMENT '合同总额',
    MODIFY COLUMN currency VARCHAR(8) NOT NULL DEFAULT 'CNY' COMMENT '币种',
    MODIFY COLUMN remark VARCHAR(2000) NULL COMMENT '备注',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE contract_line COMMENT = '合同行';
ALTER TABLE contract_line
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN contract_id BIGINT NOT NULL COMMENT '合同头ID',
    MODIFY COLUMN line_no INT NOT NULL COMMENT '行号',
    MODIFY COLUMN material_id BIGINT NULL COMMENT '物料ID',
    MODIFY COLUMN material_desc VARCHAR(255) NULL COMMENT '物料说明',
    MODIFY COLUMN qty DECIMAL(19, 4) NULL COMMENT '数量',
    MODIFY COLUMN uom VARCHAR(32) NULL COMMENT '单位',
    MODIFY COLUMN unit_price DECIMAL(19, 4) NULL COMMENT '单价',
    MODIFY COLUMN amount DECIMAL(19, 4) NULL COMMENT '金额',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '行备注',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
